/* MODELAGEM 1ª FORMA NORMAL */
'''
1 - Todo campo vetorizado se tornará outra tabela
    EX.:    [AMARELO, AZUL, VERDE, VERMELHO] -> CORES
            [CIRCULO, TRIANGULO, QUADRADO] -> FORMAS GEOMÉTRICAS

2 - Todo campo multivalorado se tornará outra tabela ou quando o campo for divisível

3 - Toda tabela necessita de pelo menos um campo que indentifique todo o registro como sendo único.
    Isso é o que chamamos de "CHAVE PRIMARIA" ou PRIMARY KEY.



