CREATE DATABASE TIME;

-- VERIFICANDO AS CHAVES
SHOW CREATE DATABASE TIME;
'''
+----------+-----------------------------------------------------------------+
| Database | Create Database                                                 |
+----------+-----------------------------------------------------------------+
| time     | CREATE DATABASE `time` /*!40100 DEFAULT CHARACTER SET latin1 */ |
+----------+-----------------------------------------------------------------+
1 row in set (0.00 sec)
'''
