/*  UTILIZANDO O UPDATE PARA ATUALIZAR VALORES  */

USE CLIENTE;

SELECT NOME, EMAIL
FROM CLIENTE;
'''
+--------+-----------------+
| NOME   | EMAIL           |
+--------+-----------------+
| JORGE  | NULL            |
| JOAO   | JOAO@GMAIL.COM  |
| LILIAN | NULL            |
| ANA    | ANA@GMAIL.COM   |
| CARLA  | CARLA@GMAIL.COM |
| CELIA  | CELIA@GMAIL.COM |
+--------+-----------------+
6 rows in set (0.00 sec)'''

